### ISSUE TITLE
all skins error 500 

### ISSUE THREAD

**Issue by fbstj** [jdlrobson/SimpleSkins#1]
I know this is probably still a WIP and isn't meant to actually work, but I couldn't get it to work XD

**Comment by jdlrobson** [comment]
Could you clarify what the server 500 error is for and confirm which version of MediaWiki you are using? It needs Mustache so it relies on a more recent version of MediaWiki. It's workng fine for me so keen to understand this problem!

**Comment by fbstj** [comment]
ahhh ok that's probably why, I'm a few versions behind (like 25.1 or something...ok I'm actually on 1.24.0 oops)

BTW: this looks like a really cool project, thanks for doing it
